# -*- coding: utf-8 -*-
"""Assignment1 - raw_house_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZq_Fo0DgR9OxJhZzVWADD2KSoNCXanL

#ASSIGNMENT 1

##LOAD LIBRARIES
"""

import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

print("--- Pandas version ---")
print(pd.__version__)
print("--- Seaborn ---")
print(sns.__version__)
print("--- MatPlotLib ---")
print(mpl.__version__)

"""##LOAD THE HEADERS"""

raw_house_data = '/content/raw_house_data.csv'
headers = pd.read_csv(raw_house_data, nrows=0)
print("--- HEADERS ---")
print(headers)
print("--- HEADERS COLUMNS ---")
print(headers.columns)
print("--- HEADERS COLUMNS TOLIST---")
print(headers.columns.tolist())
print("--- HEADERS PRINT ---")
for title in headers.columns.tolist():
  print(title)

"""##LOAD THE DATA"""

X_columns_to_read = ['MLS', 'sold_price', 'zipcode', 'longitude', 'latitude', 'lot_acres', 'taxes', 'year_built', 'bedrooms', 'bathrooms', 'sqrt_ft', 'garage', 'kitchen_features', 'fireplaces', 'floor_covering', 'HOA']
X = pd.read_csv(raw_house_data, usecols=X_columns_to_read)

"""##OVERVIEW OF DATA"""

print("--- X.shape ---")
print(X.shape)
print("--- X.info() ---")
X.info()

print("--- NUMBER OF ROWS ---")
num_of_rows = X.shape[0]
print(num_of_rows)
print("--- Number of non-null values ---")
print(X.count())

print("--- X.dtypes ---")
X.dtypes

print("--- X.describe() ---")
X.describe()

print("--- X ---")
X

"""##CLEANING THE DATA"""

total_observations_removed = 0
print("--- TOTAL OBSERVATIONS REMOVED ---")
print(total_observations_removed)

"""###CLEAN COLUMN 'lot_acres'"""

def overview_of_data_distribution_for_column(X, column_name):
  print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'lot_acres' ---")
  number_na_lot_acres = X[column_name].isna().sum()
  print("--- Number of NAs ---")
  print(number_na_lot_acres)
  count_zeros_lot_acres = 0
  between_0_100_lot_acres = 0
  between_100_1000_lot_acres = 0
  greater_than_1000_lot_acres = 0
  for index, row in X[column_name].items():
    if pd.notnull(row):
      if row == 0:
        count_zeros_lot_acres += 1
      elif row > 0 and row < 100:
        between_0_100_lot_acres += 1
      elif row > 100 and row <= 1000:
        between_100_1000_lot_acres += 1
      else:
        greater_than_1000_lot_acres += 1
  print("--- Number of zeros ---")
  print(count_zeros_lot_acres)
  print("--- Number less than 100 ---")
  print(between_0_100_lot_acres)
  print("--- Number less than 1000 ---")
  print(between_100_1000_lot_acres)
  print("--- Number greater than 1000 ---")
  print(greater_than_1000_lot_acres)

sns.boxplot(data=X, x='lot_acres', orient='h')

overview_of_data_distribution_for_column(X, 'lot_acres')

print("--- REMOVING OUTLIERS OF 'lot_acres' ---")
total_to_remove = 3
for count in range(total_to_remove):
  print("count: " + str(count))
  maximum_in_lot_acres = X['lot_acres'].max()
  print("MAX: " + str(maximum_in_lot_acres))
  for row in X['lot_acres'].index:
    if X['lot_acres'][row] == maximum_in_lot_acres:
      X.drop(row, inplace=True)
      total_observations_removed += 1
print("--- TOTAL OBSERVATIONS REMOVED ---")
print(total_observations_removed)

print("--- FINDING AVERAGE OF COLUMN 'lot_acres' IGNORING 0s AND NULLS ---")
print("--- AVERAGE BEFORE (INCLUDES ZEROS) ---")
print(X['lot_acres'].mean())
print("--- SUM OF LOT ACRES ---")
count_no_nulls_lot_acres = X['lot_acres'].count()
sum_lot_acres = X['lot_acres'].sum()
print(count_no_nulls_lot_acres)
print(sum_lot_acres)
number_na_lot_acres = X['lot_acres'].isna().sum()
number_zeros_lot_acres = 0
for row in X['lot_acres']:
  if row == 0:
    number_zeros_lot_acres += 1
print("--- NUMBER OF ZEROS FOUND IN 'lot_acres' ---")
print(number_zeros_lot_acres)
print("--- AVERAGE OF LOT ACRES MINUS 0s AND NULLS ---")
average_no_zeros_lot_acres = sum_lot_acres/(count_no_nulls_lot_acres - number_zeros_lot_acres)
print(average_no_zeros_lot_acres)

print("--- REPLACING ZEROS AND NULLS WITH NEW AVERAGE IN 'lot_acres' ---")
X.fillna({'lot_acres':average_no_zeros_lot_acres}, inplace=True)
X.loc[X['lot_acres'] == 0, 'lot_acres'] = average_no_zeros_lot_acres

overview_of_data_distribution_for_column(X, 'lot_acres')

sns.boxplot(data=X, x='lot_acres', orient='h')

"""###CLEAN COLUMN 'taxes'"""

sns.boxplot(data=X, x='taxes', orient='h')

print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'taxes' ---")
print("--- MAX VALUE IN 'taxes' ---")
print(X['taxes'].max())
maximum_value_taxes = X['taxes'].max()
for row in X.index:
  if X.loc[row,'taxes'] == maximum_value_taxes:
    X.drop(row, inplace=True)
    total_observations_removed += 1
print("--- NEW MAX VALUE IN 'taxes' ---")
print(X['taxes'].max())
print("--- TOTAL OBSERVATIONS REMOVED ---")
print(total_observations_removed)

sns.boxplot(data=X, x='taxes', orient='h')

print("--- MAX VALUE IN 'taxes' ---")
print(X['taxes'].max())
maximum_value_taxes = X['taxes'].max()
for row in X.index:
  if X.loc[row,'taxes'] == maximum_value_taxes:
    X.drop(row, inplace=True)
    total_observations_removed += 1
print("--- NEW MAX VALUE IN 'taxes' ---")
print(X['taxes'].max())
print("--- TOTAL OBSERVATIONS REMOVED ---")
print(total_observations_removed)

sns.boxplot(data=X, x='taxes', orient='h')

"""###CLEAN COLUMN 'year_built'"""

def overview_of_data_distribution_for_year_built(X):
  print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'year_built' ---")
  print("--- Number of NAs ---")
  print(X['year_built'].isna().sum())
  print("--- Minimum in 'year_built' ---")
  print(X['year_built'].min())
  count_zeros_year_built = 0
  less_than_1900_year_built = 0
  between_1900_1950_year_built = 0
  between_1950_2000_year_built = 0
  between_2000_2025_year_built = 0
  greater_than_2025_year_built = 0
  for row in X['year_built']:
    if row == 0:
      count_zeros_year_built += 1
    elif row > 0 and row < 1900:
      less_than_1900_year_built += 1
    elif row >= 1900 and row < 1950:
      between_1900_1950_year_built += 1
    elif row >= 1950 and row < 2000:
      between_1950_2000_year_built += 1
    elif row >= 2000 and row < 2025:
      between_2000_2025_year_built += 1
    else:
      greater_than_2025_year_built += 1
  print("--- Number of zeros ---")
  print(count_zeros_year_built)
  print("--- Number less than 1900 ---")
  print(less_than_1900_year_built)
  print("--- Number between 1900 and 1950 ---")
  print(between_1900_1950_year_built)
  print("--- Number between 1950 and 2000 ---")
  print(between_1950_2000_year_built)
  print("--- Number between 2000 and 2025 ---")
  print(between_2000_2025_year_built)
  print("--- Number greater than 2025 ---")
  print(greater_than_2025_year_built)

overview_of_data_distribution_for_year_built(X)

print("--- FIND NEW AVERAGE WITHOUT 0s IN 'year_built' ---")
number_na = X['year_built'].isna().sum()
sum_year_built = X['year_built'].sum()
count_zeros_year_built = 0
for row in X['year_built']:
    if row == 0:
      count_zeros_year_built += 1
number_without_0_year_built = X['year_built'].count() - count_zeros_year_built
print("--- AVERAGE BEFORE ---")
print(X['year_built'].mean())
new_average_year_built = sum_year_built/number_without_0_year_built
X['year_built'] = X['year_built'].astype(float)
print("--- REPLACE 0s in 'year_built' WITH NEW AVERAGE ---")
X.loc[X['year_built'] == 0, 'year_built'] = new_average_year_built
print("--- AVERAGE AFTER ---")
print(X['year_built'].mean())

overview_of_data_distribution_for_year_built(X)

"""###CLEAN COLUMN 'bedrooms'"""

sns.boxplot(data=X, x='bedrooms', orient='h')

print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'bedrooms' ---")
maximum_bedrooms = X['bedrooms'].max()
print("--- MAXIMUM 'bedrooms' ---")
print(maximum_bedrooms)
for row in X['bedrooms'].index:
  if X.loc[row,'bedrooms'] == maximum_bedrooms:
    X.drop(row, inplace=True)
    total_observations_removed += 1
maximum_bedrooms = X['bedrooms'].max()
print("--- NEW MAXIMUM 'bedrooms' ---")
print(maximum_bedrooms)
print("--- TOTAL OBSERVATIONS REMOVED ---")
print(total_observations_removed)

sns.boxplot(data=X, x='bedrooms', orient='h')

"""###CLEAN COLUMN 'bathrooms'"""

print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'bathrooms' ---")
print("--- AVEAGE OF 'bathrooms' ---")
print(X['bathrooms'].mean())
print("--- NUMBER OF NAs IN 'bathrooms' ---")
print(X['bathrooms'].isna().sum())
number_zeros_bathrooms = 0
for row in X['bathrooms']:
  if row == 0:
    number_zeros_bathrooms += 1
print("--- NUMBER OF ZEROS IN 'bathrooms' ---")
print(number_zeros_bathrooms)

print("--- REPLACING NULLS WITH AVERAGE IN 'bathrooms' ---")
X.fillna({'bathrooms':X['bathrooms'].mean()}, inplace=True)
print("--- NUMBER OF NAs IN 'bathrooms' ---")
print(X['bathrooms'].isna().sum())

sns.boxplot(data=X, x='bathrooms', orient='h')

print("--- REMOVING OUTLIER IN 'bathrooms' ---")
maximum_bathrooms = X['bathrooms'].max()
print("--- MAXIMUM 'bathrooms' ---")
print(maximum_bathrooms)
for row in X['bathrooms'].index:
  if X['bathrooms'][row] == maximum_bathrooms:
    if X.loc[row,'bathrooms'] == maximum_bathrooms:
      X.drop(row, inplace=True)
      total_observations_removed += 1
print("--- NEW MAXIMUM 'bathrooms' ---")
print(X['bathrooms'].max())
print("--- TOTAL OBSERVATIONS REMOVED ---")
print(total_observations_removed)

sns.boxplot(data=X, x='bathrooms', orient='h')

"""###CLEAN COLUMN 'sqrt_ft'"""

print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'sqrt_ft' ---")
print("--- AVEAGE OF 'sqrt_ft' ---")
print(X['sqrt_ft'].mean())
print("--- NUMBER OF NAs IN 'sqrt_ft' ---")
print(X['sqrt_ft'].isna().sum())
number_zeros_sqrt_ft = 0
for row in X['sqrt_ft']:
  if row == 0:
    number_zeros_bathrooms += 1
print("--- NUMBER OF ZEROS IN 'sqrt_ft' ---")
print(number_zeros_sqrt_ft)

print("--- REPLACING NULLS WITH AVERAGE IN 'sqrt_ft' ---")
X.fillna({'sqrt_ft':X['sqrt_ft'].mean()}, inplace=True)
print("--- NUMBER OF NAs IN 'sqrt_ft' ---")
print(X['sqrt_ft'].isna().sum())

"""###CLEAN COLUMN 'garage'"""

print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'garage' ---")
print("--- AVEAGE OF 'garage' ---")
print(X['garage'].mean())
print("--- NUMBER OF NAs IN 'garage' ---")
print(X['garage'].isna().sum())
number_zeros_garage = 0
for row in X['garage']:
  if row == 0:
    number_zeros_garage += 1
print("--- NUMBER OF ZEROS IN 'garage' ---")
print(number_zeros_garage)

print("--- REPLACING NULLS WITH 0 IN 'garage' ---")
X.fillna({'garage': 0}, inplace=True)
print("--- AVEAGE OF 'garage' ---")
print(X['garage'].mean())
print("--- NUMBER OF NAs IN 'garage' ---")
print(X['garage'].isna().sum())
number_zeros_garage = 0
for row in X['garage']:
  if row == 0:
    number_zeros_garage += 1
print("--- NUMBER OF ZEROS IN 'garage' ---")
print(number_zeros_garage)

"""###CLEAN COLUMN 'kitchen_features'"""

print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'kitchen_features' ---")
print("--- NUMBER OF NAs IN 'kitchen_features' BEFORE REPLACEMENT WITH 'None' ---")
print(X['kitchen_features'].isna().sum())
X.fillna({'kitchen_features':"None"}, inplace=True)
print("--- NUMBER OF NAs IN 'kitchen_features' AFTER REPLACEMENT WITH 'None' ---")
print(X['kitchen_features'].isna().sum())

kitchen_features_dict = dict()
for row in X['kitchen_features'].index:
  features_list = [feature.strip() for feature in list(X.loc[row, 'kitchen_features'].split(','))]
  features_list.sort()
  features_word = ','.join(features_list)
  X.loc[row, 'kitchen_features'] = features_word
  kitchen_features_dict[features_word] = kitchen_features_dict.setdefault(features_word, 0)+1
print("--- NUMBER OF 'None' IN 'kitchen_features' ---")
print(kitchen_features_dict["None"])
print("--- NUMBER OF DIFFERENT LISTS IN 'kitchen_features' ---")
print(len(kitchen_features_dict))

"""###CLEAN COLUMN 'fireplaces'"""

print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'fireplaces' ---")
print("--- NUMBER OF NAs IN 'fireplaces' BEFORE ---")
print(X['fireplaces'].isna().sum())
X['fireplaces'] = pd.to_numeric(X['fireplaces'], errors='coerce')
print(type(X['fireplaces']))
print(type(X['fireplaces'][10]))
print("--- NUMBER OF NAs IN 'fireplaces' AFTER ---")
X.fillna({'fireplaces': 0}, inplace=True)
print(X['fireplaces'].isna().sum())
equal_0_fireplaces = 0
between_0_5_fireplaces = 0
greater_5_fireplaces = 0
for row in X['fireplaces']:
  if row == 0:
    equal_0_fireplaces += 1
  elif row > 0 and row <= 5:
    between_0_5_fireplaces += 1
  else:
    greater_5_fireplaces += 1
print("---  COUNT == 0 'fireplaces' ---")
print(equal_0_fireplaces)
print("---  COUNT BETWEEN 0 AND 5 'fireplaces' ---")
print(between_0_5_fireplaces)
print("---  COUNT > 5 'fireplaces' ---")
print(greater_5_fireplaces)
print("--- MIN VALUE IN 'fireplaces' ---")
print(X['fireplaces'].min())
print("--- MAX VALUE IN 'fireplaces' ---")
print(X['fireplaces'].max())

"""###CLEAN COLUMN 'floor_covering'"""

print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'floor_covering' ---")
print("--- NUMBER OF NAs IN 'floor_covering' BEFORE REPLACEMENT WITH 'None' ---")
print(X['floor_covering'].isna().sum())
X.fillna({'floor_covering':"None"}, inplace=True)
print("--- NUMBER OF NAs IN 'floor_covering' AFTER REPLACEMENT WITH 'None' ---")
print(X['floor_covering'].isna().sum())

floor_covering_dict = dict()
for row in X['floor_covering'].index:
  floor_covering_list = [covering.strip() for covering in list(X.loc[row, 'floor_covering'].split(','))]
  floor_covering_list.sort()
  floor_covering_word = ','.join(floor_covering_list)
  X.loc[row, 'floor_covering'] = floor_covering_word
  floor_covering_dict[floor_covering_word] = floor_covering_dict.setdefault(floor_covering_word, 0)+1
print("--- NUMBER OF 'None' IN 'floor_covering' ---")
print(floor_covering_dict["None"])
print("--- NUMBER OF DIFFERENT LISTS IN 'floor_covering' ---")
print(len(floor_covering_dict))

"""###CLEAN COLUMN 'HOA'"""

print("--- OVERVIEW OF DATA DISTRIBUTION FOR 'HOA' ---")
print("--- NUMBER OF NAs in 'HOA' ---")
print(X['HOA'].isna().sum())
X.fillna({'HOA':-1}, inplace=True)
print("--- REPLACING NAs WITH -1s ---")
print("--- NUMBER OF NAs IN 'HOA' AFTER REPLACMENT ---")
print(X['HOA'].isna().sum())

sns.boxplot(data=X, x='HOA', orient='h')

number_to_remove_HOA = 4
for count in range(number_to_remove_HOA):
  maximum_HOA = X['HOA'].max()
  print("--- MAXIMUM HOA ---")
  print(maximum_HOA)
  for row in X['HOA'].index:
    if X.loc[row,'HOA'] == maximum_HOA:
      X.drop(row, inplace=True)
      total_observations_removed += 1

print("--- NEW MAXIMUM 'HOA' ---")
print(X['HOA'].max())
print("--- TOTAL OBSERVATIONS REMOVED ---")
print(total_observations_removed)

sns.boxplot(data=X, x='HOA', orient='h')

"""###REMOVE DUPLICATES FROM DATAFRAME"""

print("--- X SHAPE ---")
print(X.shape)
rows_before_dup_removal = X.shape[0]
print("--- REMOVING DUPLICATES ---")
X.drop_duplicates(inplace=True)
rows_after_dup_removal = X.shape[0]
total_dups_removed = rows_before_dup_removal - rows_after_dup_removal
total_observations_removed -= total_dups_removed
print("--- X SHAPE ---")
print(X.shape)
print("--- TOTAL OBSERVATIONS REMOVED ---")
print(total_observations_removed)

"""##SAVING CLEANED DATA TO NEW CSV FILE"""

raw_house_data_cleaned = '/content/raw_house_data_cleaned.csv'
X.to_csv(raw_house_data_cleaned, index=False)

"""##VISUALIZING THE DATA

###RENAMED HEADERS FOR GRAPHING
"""

headers_to_boxplot = [header for header in X.columns.tolist() if header not in ['MLS','longitude','latitude']]
X=X.rename(columns={'sold_price':'Sold Price','zipcode':'ZIP Code','longitude':'Longitude','latitude':'Latitude','lot_acres':'Lot Acres',
                  'taxes':'Taxes','year_built':'Year Built','bedrooms':'Bedrooms','bathrooms':'Bathrooms','sqrt_ft':'Square Footage',
                  'garage':'Garage','kitchen_features':'Kitchen Features','fireplaces':'Fireplaces','floor_covering':'Floor Covering'})
print(X.columns.tolist())

"""###HISTOGRAMS"""

X['Sold Price'].plot(kind = 'hist')

X['ZIP Code'].plot(kind = 'hist')

X['Longitude'].plot(kind = 'hist')

X['Latitude'].plot(kind = 'hist')

X['Lot Acres'].plot(kind = 'hist')

X['Taxes'].plot(kind = 'hist')

X['Year Built'].plot(kind = 'hist')

X['Bedrooms'].plot(kind = 'hist')

X['Bathrooms'].plot(kind = 'hist')

X['Square Footage'].plot(kind = 'hist')

X['Garage'].plot(kind = 'hist')

X['Fireplaces'].plot(kind = 'hist')

X['HOA'].plot(kind = 'hist')

"""###PAIR PLOTS"""

headers_to_plot = ['Sold Price', 'ZIP Code', 'Longitude', 'Latitude', 'Lot Acres', 'Taxes', 'Year Built', 'Bedrooms', 'Bathrooms', 'Square Footage', 'Garage', 'Fireplaces', 'HOA']
features_to_plot = X.loc[:, headers_to_plot]
print("--- features_to_plot.info() ---")
features_to_plot.info()

sns.pairplot(features_to_plot)

"""###HEATMAP"""

fig, ax = plt.subplots(figsize=(15, 10))
sns.heatmap(features_to_plot.corr(), cmap="BrBG", annot=True, linewidths=.5, ax=ax)

"""###BOXPLOTS"""

sns.boxplot(data=X, x='Sold Price', orient='h')

sns.boxplot(data=X, x='ZIP Code', orient='h')

sns.boxplot(data=X, x='Longitude', orient='h')

sns.boxplot(data=X, x='Latitude', orient='h')

sns.boxplot(data=X, x='Lot Acres', orient='h')

sns.boxplot(data=X, x='Taxes', orient='h')

sns.boxplot(data=X, x='Year Built', orient='h')

sns.boxplot(data=X, x='Bedrooms', orient='h')

sns.boxplot(data=X, x='Bathrooms', orient='h')

sns.boxplot(data=X, x='Square Footage', orient='h')

sns.boxplot(data=X, x='Garage', orient='h')

sns.boxplot(data=X, x='Fireplaces', orient='h')

sns.boxplot(data=X, x='HOA', orient='h')